#!/bin/sh

# Author: Matthias Maderer
# E-Mail: edvler@edvler-blog.de
# URL: https://github.com/edvler/check_mk-zfs_zrep_status
# License: GPLv2

ZREP_BINARY=zrep

echo '<<<zfs_zrep_status>>>'

$ZREP_BINARY status

