#!/usr/bin/python

# Author: Matthias Maderer
# E-Mail: edvler@edvler-blog.de
# URL: https://github.com/edvler/check_mk-zfs_zrep_status
# License: GPLv2


# default parameters
zfs_zrep_status_default_levels = {'check_backup': 'check', 'backup_age': (93600, 108000)}

# the inventory function (dummy)
def inventory_zfs_zrep_status(info):
    # loop over all output lines of the agent
    for line in info:
        yield line[0] + ' Tag: ' + line[4], "zfs_zrep_status_default_levels"
        #yield line[0], "zfs_zrep_status_default_levels"

# the check function (dummy)
def check_zfs_zrep_status(item, params, info):
    #return 0 if check of backups should not be done
    if params['check_backup'] == 'ignore':
        return 0, 'check disabled by rule'

    for line in info:
        if line[0] + ' Tag: ' + line[4] == item:
            synctime = time.strptime(line[3],"%Y/%m/%d-%H:%M:%S")

            old = time.time() - time.mktime(synctime)
            duration_formatted = pretty_time_delta(old)
            infotext = 'last synchronized: ' + time.strftime("%Y-%m-%d %H:%M", synctime) + ' (' + duration_formatted + ' ago)'

            warn, error = params['backup_age']

            if old >= error:
                return 2, infotext
            if old >= warn:
                return 1, infotext

            return 0, infotext

    return 3, 'zrep status returned no output for ' + item + '. Maybe the ZFS dataset was removed or zrep clear was called?'



# declare the check to Check_MK
check_info["zfs_zrep_status"] = {
    'check_function':            check_zfs_zrep_status,
    'inventory_function':        inventory_zfs_zrep_status,
    'service_description':       'ZREP status',
    'group':                     'zfs',
}

#thanks to https://gist.github.com/thatalextaylor/7408395
def pretty_time_delta(seconds):
    sign_string = '-' if seconds < 0 else ''
    seconds = abs(int(seconds))
    days, seconds = divmod(seconds, 86400)
    hours, seconds = divmod(seconds, 3600)
    minutes, seconds = divmod(seconds, 60)
    if days > 0:
        return '%s%d days %d hours %d minutes' % (sign_string, days, hours, minutes)
    elif hours > 0:
        return '%s%d hours %d minutes' % (sign_string, hours, minutes)
    elif minutes > 0:
        return '%s%d minutes' % (sign_string, minutes)
    else:
        return '0 minutes'

#Example output of agent
#
#root@pve01:/usr/lib/check_mk_agent/plugins# ./zfs_zrep_status
#<<<zfs_zrep_status>>>
#backup01/testbla                               last synced 2018/10/03-16:53:10
#backup02/offsite                               last synced 2018/10/03-12:01:29

